# Generated by Django 5.1.6 on 2025-04-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
