# Generated by Django 5.1.6 on 2025-12-21 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_usermodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=3, verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.currency'),
        ),
    ]
