# Generated by Django 5.1.6 on 2025-04-23 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_category_unique_together_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.category'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='category_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.category'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type_en',
            field=models.CharField(choices=[('INCOME', 'Income'), ('OUTCOME', 'Outcome')], default='OUTCOME', max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type_ru',
            field=models.CharField(choices=[('INCOME', 'Income'), ('OUTCOME', 'Outcome')], default='OUTCOME', max_length=20, null=True, verbose_name='Type'),
        ),
    ]
