# Generated by Django 5.1.6 on 2025-04-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_remove_transaction_category_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type_ru',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type_en',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='type_ru',
        ),
    ]
