# Generated by Django 5.1.6 on 2025-04-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_remove_category_name_en_remove_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='type_en',
            field=models.CharField(choices=[('INCOME', 'Income'), ('OUTCOME', 'Outcome')], default='OUTCOME', max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='category',
            name='type_ru',
            field=models.CharField(choices=[('INCOME', 'Income'), ('OUTCOME', 'Outcome')], default='OUTCOME', max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type_en',
            field=models.CharField(choices=[('INCOME', 'Income'), ('OUTCOME', 'Outcome')], default='OUTCOME', max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='type_ru',
            field=models.CharField(choices=[('INCOME', 'Income'), ('OUTCOME', 'Outcome')], default='OUTCOME', max_length=20, null=True, verbose_name='Type'),
        ),
    ]
