# Generated by Django 5.1.6 on 2025-12-21 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0014_remove_budget_total_income_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
    ]
